// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/funnel": {
            "post": {
                "description": "Start tailscale funnel on specified port",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tailscale"
                ],
                "summary": "Start funnel",
                "parameters": [
                    {
                        "description": "Funnel configuration",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_delivery_http.FunnelRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_delivery_http.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_delivery_http.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_delivery_http.Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "Reset tailscale funnel configuration",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tailscale"
                ],
                "summary": "Reset funnel",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_delivery_http.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_delivery_http.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/funnel/status": {
            "get": {
                "description": "Get current tailscale funnel configuration",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tailscale"
                ],
                "summary": "Get funnel status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_delivery_http.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_delivery_http.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/logs/app": {
            "get": {
                "description": "Get application log file content",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "logs"
                ],
                "summary": "Get application logs",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 100,
                        "description": "Number of lines to retrieve",
                        "name": "lines",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_delivery_http.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_delivery_http.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/serve": {
            "post": {
                "description": "Start tailscale serve on specified port",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tailscale"
                ],
                "summary": "Start serve",
                "parameters": [
                    {
                        "description": "Serve configuration",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_delivery_http.ServeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_delivery_http.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_delivery_http.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_delivery_http.Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "Reset tailscale serve configuration",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tailscale"
                ],
                "summary": "Reset serve",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_delivery_http.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_delivery_http.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/serve/status": {
            "get": {
                "description": "Get current tailscale serve configuration",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tailscale"
                ],
                "summary": "Get serve status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_delivery_http.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_delivery_http.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/ssh/enable": {
            "post": {
                "description": "Enable tailscale SSH access",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tailscale"
                ],
                "summary": "Enable SSH",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_delivery_http.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_delivery_http.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/status": {
            "get": {
                "description": "Get current tailscale connection status",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tailscale"
                ],
                "summary": "Get tailscale status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_delivery_http.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_delivery_http.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "internal_delivery_http.FunnelRequest": {
            "type": "object",
            "required": [
                "port"
            ],
            "properties": {
                "background": {
                    "type": "boolean"
                },
                "port": {
                    "type": "integer"
                }
            }
        },
        "internal_delivery_http.Response": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "internal_delivery_http.ServeRequest": {
            "type": "object",
            "required": [
                "port"
            ],
            "properties": {
                "background": {
                    "type": "boolean"
                },
                "port": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Tailscale Controller API",
	Description:      "Self-contained HTTP API for Tailscale with embedded daemon",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
